name: Extract value from JSON
description: Extracts a value of a property specified as dot-separated path from defined JSON file
author: "amochkin"
inputs:
  file:
    description: "Path to JSON file (defaults `package.json`)"
  property:
    description: "Dot-separated path to property (for example `a.b`)"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: alert-circle
  color: blue
outputs:
  value:
    description: "Value of property"