name: Manual Tests

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'JSON File (relative to root)'
        default: 'package.json'
      property:
        description: 'JSON Property (dot separated)'
        default: 'version'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run action
        uses: amochkin/gha-json-value@latest
        id: test
        with:
          file: ${{ github.event.inputs.file }}
          property: ${{ github.event.inputs.property }}